### ISSUE TITLE
weird timing issue with file_test.go / remove tmpfile debugging

### ISSUE THREAD

**Issue by phillmv** [stateio/canary-agent#31]
About 20% of the time [`TestWatchFileHookLoop`](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L92) will just hang until the go test utility kills the test because of a timeout.

The remainder of the time it works as intended. 

## Current hypothesis 
The timer in the [inner go routine](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L115) won't fire For Reasons.

That's as far as I've been able to determine; the test will run, all of the right files get written to, the callbacks fire - except for the timers. I've narrowed down on the timers because, on the trial runs where the test fails, the debug "print" statements near the timer code never show up. 

On successful runs, the output file becomes filled with [`"microloop"`](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L130) print statements.

If on the failing runs the loop never writes to `invokedCount`, that would explain why the test [hangs and never exits](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L201).

(Not only that, but hanging tests won't print to stdout, thus forcing me to resource to all the write calls to `/tmp/wtf` as a means of getting debugging values)

### reproduce
I can reproduce this some of the time by running the test:
```
make testr t=WatchFileHookLoop
```
and in a separate terminal tab,

```
touch /tmp/wtf && tail -f /tmp/wtf
```

Once this gets cleaned up, it'd be real smart to get rid of all of the `/tmp/wtf` calls.

**Comment by shazow** [comment]
So I just ran:

```
$ while true; do go test -v ./... -run WatchFileHookLoop; done
```

And did the touch/tail in another tab for a few minutes, and it didn't hang. How do I reproduce? (This is on OSX.)

**Comment by shazow** [comment]
I can't get the test to fail, and tailing /tmp/wtf isn't showing anything. This is on go v1.4.2 on OSX. What are you running?

**Comment by shazow** [comment]
Ooooh WIP branch, nm.

**Comment by phillmv** [comment]
Ya sorry could've been more obvious

**Comment by shazow** [comment]
I don't think you need the [goroutine here](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L115-L141).

I'd replace [the testcb](https://github.com/stateio/canary-agent/blob/wip/agent/models/file_test.go#L109-L111) with something like:

```go
        counter := 0
	testcb := func(nop *WatchedFile) {
                counter++
		cbInvoked <- true
	} 
```

It's technically a race condition but you can wrap a lock around it later if you want.

I think the amount of complexity you're adding here by chaining channels is obfuscating the problem (or even causing the problem).

**Comment by phillmv** [comment]
Problem turned out to be an unbuffered channel allied to a mysterious extra write; that 20% of the time the program gets an extra write, causing the counter to move to 7. 

Because the channel was unbuffered, during these mystery writes we end up hanging the program.

The cause of the hang established, we replaced it with your loop ;)
