### ISSUE TITLE
retry upload when 500 error

### ISSUE THREAD

**Issue by mveytsman** [stateio/canary-agent#42]
got this in testing from the server

I think maybe we uploaded a partially complete file somehow?

2015-Jun-11 13:44:47 -0700 nabokov.local ERROR [canary.web.utils] - Error in PUT "/api/v1/agent/servers/5579eaf6-2b5e-4f20-add8-9f2dcf4f3cd2" for 127.0.0.1 at Thu Jun 11 13:44:47 PDT 2015 #error {
 :cause -1
 :via
 [{:type java.lang.ArrayIndexOutOfBoundsException
   :message -1
   :at [base64_clj.core$decode_bytes invoke core.clj 106]}]
 :trace
 [[base64_clj.core$decode_bytes invoke core.clj 106]
  [base64_clj.core$decode invoke core.clj 125]
  [base64_clj.core$decode invoke core.clj 123]
  [canary.web.routes.agent$fn__22446$fn__22457$fn__22458 invoke agent.clj 70]
  [canary.web.auth$fn__21965$require_auth__21966$fn__21967$fn__21968 invoke auth.clj 29]
  [buddy.auth.middleware$wrap_authentication$fn__20966 invoke middleware.clj 39]
  [buddy.auth.middleware$wrap_authorization$fn__20973 invoke middleware.clj 73]
  [canary.web.routes.agent$fn__22446$fn__22457 invoke agent.clj 56]
  [compojure.core$make_route$fn__17692 invoke core.clj 113]
  [compojure.core$wrap_route_middleware$fn__17688 invoke core.clj 103]
  [compojure.core$if_route$fn__17671 invoke core.clj 41]
  [compojure.core$if_method$fn__17663 invoke core.clj 27]
  [compojure.api.meta$body_coercer_middleware$fn__18645 invoke meta.clj 56]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invoke core.clj 630]
  [compojure.core$routes$fn__17702 invoke core.clj 132]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [canary.web.routes.agent$fn__22446 invoke agent.clj 40]
  [compojure.core$if_context$fn__17720 invoke core.clj 194]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invoke core.clj 630]
  [compojure.core$routes$fn__17702 invoke core.clj 132]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.lang.AFunction$1 doInvoke AFunction.java 29]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.lang.Var invoke Var.java 379]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invoke core.clj 630]
  [compojure.core$routes$fn__17702 invoke core.clj 132]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [canary.web.handler$fn__10168 invoke handler.clj 49]
  [compojure.core$if_context$fn__17720 invoke core.clj 194]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invoke core.clj 630]
  [compojure.core$routes$fn__17702 invoke core.clj 132]
  [canary.web.utils$eval6284$ignore_trailing_slash__6285$fn__6286$fn__6287 invoke utils.clj 187]
  [canary.web.utils$eval6240$wrap_logging__6241$fn__6242$fn__6243 invoke utils.clj 170]
  [compojure.core$routing$fn__17698 invoke core.clj 127]
  [clojure.core$some invoke core.clj 2568]
  [compojure.core$routing doInvoke core.clj 127]
  [clojure.lang.RestFn applyTo RestFn.java 139]
  [clojure.core$apply invoke core.clj 630]
  [compojure.core$routes$fn__17702 invoke core.clj 132]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.lang.AFunction$1 doInvoke AFunction.java 29]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [ring.swagger.middleware$wrap_swagger_data$fn__19909 invoke middleware.clj 33]
  [ring.middleware.http_response$wrap_http_response$fn__19766 invoke http_response.clj 8]
  [ring.swagger.middleware$wrap_validation_errors$fn__19934 invoke middleware.clj 68]
  [compojure.api.middleware$wrap_exceptions$fn__19959 invoke middleware.clj 53]
  [ring.swagger.middleware$wrap_swagger_data$fn__19909 invoke middleware.clj 33]
  [compojure.api.middleware$wrap_options$fn__19962 invoke middleware.clj 67]
  [ring.middleware.format_params$wrap_format_params$fn__19566 invoke format_params.clj 111]
  [ring.middleware.format_response$wrap_format_response$fn__19697 invoke format_response.clj 175]
  [ring.middleware.keyword_params$wrap_keyword_params$fn__19800 invoke keyword_params.clj 35]
  [ring.middleware.nested_params$wrap_nested_params$fn__19844 invoke nested_params.clj 84]
  [ring.middleware.params$wrap_params$fn__19900 invoke params.clj 64]
  [compojure.api.middleware$wrap_options$fn__19962 invoke middleware.clj 67]
  [clojure.lang.AFn applyToHelper AFn.java 154]
  [clojure.lang.AFn applyTo AFn.java 144]
  [clojure.lang.AFunction$1 doInvoke AFunction.java 29]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [canary.web.utils$eval6130$wrap_datomic__6131$fn__6135$fn__6137 invoke utils.clj 144]
  [canary.web.utils$eval6155$wrap_rubygems_api_key__6156$fn__6157$fn__6158 invoke utils.clj 153]
  [org.httpkit.server.HttpHandler run RingHandler.java 91]
  [java.util.concurrent.Executors$RunnableAdapter call Executors.java 511]
  [java.util.concurrent.FutureTask run FutureTask.java 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker ThreadPoolExecutor.java 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run ThreadPoolExecutor.java 617]
  [java.lang.Thread run Thread.java 745]]}
[1;31mjava.lang.ArrayIndexOutOfBoundsException[m: [3m-1[m
                           [33mbase64-clj.core/[1;33mdecode-bytes[m  [32m               core.clj:  106[m
                                 [33mbase64-clj.core/[1;33mdecode[m  [32m               core.clj:  125[m
                                 [33mbase64-clj.core/[1;33mdecode[m  [32m               core.clj:  123[m
                       [33mcanary.web.routes.agent/fn/fn/[1;33mfn[m  [32m              agent.clj:   70[m
                  [33mcanary.web.auth/fn/require-auth/fn/[1;33mfn[m  [32m               auth.clj:   29[m
           [33mbuddy.auth.middleware/wrap-authentication/[1;33mfn[m  [32m         middleware.clj:   39[m
            [33mbuddy.auth.middleware/wrap-authorization/[1;33mfn[m  [32m         middleware.clj:   73[m
                          [33mcanary.web.routes.agent/fn/[1;33mfn[m  [32m              agent.clj:   56[m
                           [33mcompojure.core/make-route/[1;33mfn[m  [32m               core.clj:  113[m
                [33mcompojure.core/wrap-route-middleware/[1;33mfn[m  [32m               core.clj:  103[m
                             [33mcompojure.core/if-route/[1;33mfn[m  [32m               core.clj:   41[m
                            [33mcompojure.core/if-method/[1;33mfn[m  [32m               core.clj:   27[m
          [33mcompojure.api.meta/body-coercer-middleware/[1;33mfn[m  [32m               meta.clj:   56[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                            [37mclojure.lang.RestFn.applyTo[m  [32m            RestFn.java:  139[m
                                     [33mclojure.core/[1;33mapply[m  [32m               core.clj:  630[m
                               [33mcompojure.core/routes/[1;33mfn[m  [32m               core.clj:  132[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                             [37mclojure.lang.RestFn.invoke[m  [32m            RestFn.java:  423[m
                             [33mcanary.web.routes.agent/[1;33mfn[m  [32m              agent.clj:   40[m
                           [33mcompojure.core/if-context/[1;33mfn[m  [32m               core.clj:  194[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                            [37mclojure.lang.RestFn.applyTo[m  [32m            RestFn.java:  139[m
                                     [33mclojure.core/[1;33mapply[m  [32m               core.clj:  630[m
                               [33mcompojure.core/routes/[1;33mfn[m  [32m               core.clj:  132[m
                         [37mclojure.lang.AFn.applyToHelper[m  [32m               AFn.java:  154[m
                               [37mclojure.lang.AFn.applyTo[m  [32m               AFn.java:  144[m
                      [37mclojure.lang.AFunction$1.doInvoke[m  [32m         AFunction.java:   29[m
                             [37mclojure.lang.RestFn.invoke[m  [32m            RestFn.java:  408[m
                                [37mclojure.lang.Var.invoke[m  [32m               Var.java:  379[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                            [37mclojure.lang.RestFn.applyTo[m  [32m            RestFn.java:  139[m
                                     [33mclojure.core/[1;33mapply[m  [32m               core.clj:  630[m
                               [33mcompojure.core/routes/[1;33mfn[m  [32m               core.clj:  132[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                             [37mclojure.lang.RestFn.invoke[m  [32m            RestFn.java:  423[m
                                  [33mcanary.web.handler/[1;33mfn[m  [32m            handler.clj:   49[m
                           [33mcompojure.core/if-context/[1;33mfn[m  [32m               core.clj:  194[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                            [37mclojure.lang.RestFn.applyTo[m  [32m            RestFn.java:  139[m
                                     [33mclojure.core/[1;33mapply[m  [32m               core.clj:  630[m
                               [33mcompojure.core/routes/[1;33mfn[m  [32m               core.clj:  132[m
  [33mcanary.web.utils/eval6284/ignore-trailing-slash/fn/[1;33mfn[m  [32m              utils.clj:  187[m
           [33mcanary.web.utils/eval6240/wrap-logging/fn/[1;33mfn[m  [32m              utils.clj:  170[m
                              [33mcompojure.core/routing/[1;33mfn[m  [32m               core.clj:  127[m
                                      [33mclojure.core/[1;33msome[m  [32m               core.clj: 2568[m
                                 [33mcompojure.core/[1;33mrouting[m  [32m               core.clj:  127[m
                            [37mclojure.lang.RestFn.applyTo[m  [32m            RestFn.java:  139[m
                                     [33mclojure.core/[1;33mapply[m  [32m               core.clj:  630[m
                               [33mcompojure.core/routes/[1;33mfn[m  [32m               core.clj:  132[m
                         [37mclojure.lang.AFn.applyToHelper[m  [32m               AFn.java:  154[m
                               [37mclojure.lang.AFn.applyTo[m  [32m               AFn.java:  144[m
                      [37mclojure.lang.AFunction$1.doInvoke[m  [32m         AFunction.java:   29[m
                             [37mclojure.lang.RestFn.invoke[m  [32m            RestFn.java:  408[m
           [33mring.swagger.middleware/wrap-swagger-data/[1;33mfn[m  [32m         middleware.clj:   33[m
    [33mring.middleware.http-response/wrap-http-response/[1;33mfn[m  [32m      http_response.clj:    8[m
      [33mring.swagger.middleware/wrap-validation-errors/[1;33mfn[m  [32m         middleware.clj:   68[m
            [33mcompojure.api.middleware/wrap-exceptions/[1;33mfn[m  [32m         middleware.clj:   53[m
           [33mring.swagger.middleware/wrap-swagger-data/[1;33mfn[m  [32m         middleware.clj:   33[m
               [33mcompojure.api.middleware/wrap-options/[1;33mfn[m  [32m         middleware.clj:   67[m
    [33mring.middleware.format-params/wrap-format-params/[1;33mfn[m  [32m      format_params.clj:  111[m
[33mring.middleware.format-response/wrap-format-response/[1;33mfn[m  [32m    format_response.clj:  175[m
  [33mring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  [32m     keyword_params.clj:   35[m
    [33mring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  [32m      nested_params.clj:   84[m
                  [33mring.middleware.params/wrap-params/[1;33mfn[m  [32m             params.clj:   64[m
               [33mcompojure.api.middleware/wrap-options/[1;33mfn[m  [32m         middleware.clj:   67[m
                         [37mclojure.lang.AFn.applyToHelper[m  [32m               AFn.java:  154[m
                               [37mclojure.lang.AFn.applyTo[m  [32m               AFn.java:  144[m
                      [37mclojure.lang.AFunction$1.doInvoke[m  [32m         AFunction.java:   29[m
                             [37mclojure.lang.RestFn.invoke[m  [32m            RestFn.java:  408[m
           [33mcanary.web.utils/eval6130/wrap-datomic/fn/[1;33mfn[m  [32m              utils.clj:  144[m
  [33mcanary.web.utils/eval6155/wrap-rubygems-api-key/fn/[1;33mfn[m  [32m              utils.clj:  153[m
                     [37morg.httpkit.server.HttpHandler.run[m  [32m       RingHandler.java:   91[m
    [37mjava.util.concurrent.Executors$RunnableAdapter.call[m  [32m         Executors.java:  511[m
                    [37mjava.util.concurrent.FutureTask.run[m  [32m        FutureTask.java:  266[m
      [37mjava.util.concurrent.ThreadPoolExecutor.runWorker[m  [32mThreadPoolExecutor.java: 1142[m
     [37mjava.util.concurrent.ThreadPoolExecutor$Worker.run[m  [32mThreadPoolExecutor.java:  617[m
                                   [37mjava.lang.Thread.run[m  [32m            Thread.java:  745[m

**Comment by phillmv** [comment]
fixed cos we totally changed the file watcher
